name: Bookstore API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checks out the repository code

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        # Sets up Python 3.9 for backend FastAPI

      - name: Install Python dependencies
        run: |
          pip install -r bookstore-main/requirements.txt
        # Installs FastAPI dependencies

      - name: Start FastAPI server in background
        run: |
          cd bookstore-main
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 8
        # Starts FastAPI server in background and waits for it to come up

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        # Sets up Java 17 as required by the project

      - name: Build and run tests
        run: mvn clean test
        # Runs Maven tests (will fail on test errors, as is standard in CI)

      - name: Archive Extent Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ExtentReport
          path: target/cucumber-reports/ExtentReport.html
        # Uploads Extent HTML report
